feat: register func
raihanizar/eventmakers-algorithmic pull request #20
Opened 2024-02-16 14:28 UTC by BrezyBaihaqi

dear mas @raihanizar, saya coba buat register func. tolong di review ya. terima kasih

2024-02-17 04:58 UTC, raihanizar reviewed
kena error ini nih mas @BrezyBaihaqi 
![image](https://github.com/raihanizar/eventmakers-algorithmic/assets/29392361/4a93b90a-4f80-45bb-8f4f-fa70bf64b70b)

library `js-cookie` udah diinstall kah, di `package.json` belum ada soalnya

2024-02-17 10:28 UTC, BrezyBaihaqi commented
yang register ga saya install cookies ternyata. sudah saya perbaiki mas

2024-02-17 13:28 UTC, BrezyBaihaqi commented
mas @raihanizar sudah saya coba fix ya

2024-02-17 15:25 UTC, raihanizar requested changes
@BrezyBaihaqi masih ada salah dikitt
backend register poisinya jangan di dalem **component**: `src/app/components/auth/register/page.js`
tapi lagsung di **app** aja: `src/app/register/page.js`

awalnya udah bener tapi kepindah ya kyknya wkwk

2024-02-17 15:39 UTC, BrezyBaihaqi commented
iya mas bingung jadinya hehe

2024-02-17 17:59 UTC, raihanizar requested changes
good, tinggal satu problem mas @BrezyBaihaqi, response register gaada **payload** dan **token**, coba cek di [dokumentasi API](https://eventmakers-api.fly.dev/documentation)

jadi bagian ini gak perlu, malah bikin error
```js
// save payload to local storage
localStorage.setItem("user", JSON.stringify(payload));

// store token to cookies
Cookies.set("token", token);
```

2024-02-19 14:22 UTC, raihanizar approved these changes
good lebih rapi dan gaada error

2024-02-19 14:22 UTC, merged