add create functionality
raihanizar/eventmakers-algorithmic pull request #26
Opened 2024-02-17 14:31 UTC by BrezyBaihaqi

dear mas @raihanizar mohon berkenan review ya

2024-02-17 15:36 UTC, raihanizar requested changes
Mantep lanjut pake hook, tapi tolong rapikan ya lokasi filenya ke `src/app/components/hooks/useCreateEvent.js`

Kemudian mas @BrezyBaihaqi ada ngedit `src/app/page.js`, itu utk page default. Kita sudah reserve page default utk halaman login

Nah kalo utk create event, kita bisa pakai URL `/events/form`, caranya di Next.js kita bisa buat file di `src/app/events/form/page.js`

2024-02-17 16:16 UTC, BrezyBaihaqi commented
mas @raihanizar udah saya perbaiki ya

2024-02-17 17:55 UTC, raihanizar requested changes
dapat error kyk gini
![image](https://github.com/raihanizar/eventmakers-algorithmic/assets/29392361/6f1cea65-4b08-42a8-ac08-ee83b778f610)
file `src/components/auth/components/login.jsx` di branch kok gak ada ya?

file component dan hooks harusnya gak di dalam *app*, tapi di luarnya, jadi *src* punya dua folder, *app* dan *component*, coba cek lagi panduan direktori yg ada digrup
![image](https://github.com/raihanizar/eventmakers-algorithmic/assets/29392361/cff92e4d-25de-40c9-9713-65e8166543d7)

2024-02-18 02:18 UTC, BrezyBaihaqi commented
`src/components/auth/components/login.jsx` ga ada karena itu ada di branch login, mas. jadi ga keliatan disini

2024-02-19 14:14 UTC, raihanizar approved these changes
lokasi file hook sudah betul, events form juga

masih ada error terkait kode hooks, nanti dirapikan

2024-02-19 14:14 UTC, merged