still dont work for patch and delete
raihanizar/eventmakers-algorithmic pull request #49
Opened 2024-02-24 16:28 UTC by BrezyBaihaqi

dashboard sudah muncul tapi belum berhasil untuk patch dan delete

2024-02-25 14:38 UTC, raihanizar requested changes
@BrezyBaihaqi logic dashboard udah good, lanjutkan

beberapa catatan:
- `layout.js` di folder `dashboard` kyk gak perlu, karena kita gaada template view khusus dashboard, bisa dihapus aja
- component `DeleteEvents.jsx`, `UserEvents.jsx` kyknya gak digunakan di file manapun, bisa dihapus aja kalo gak kepake
- fungsi `handleDelete()` di `UserDashboard.jsx` belum ada, tapi sudah dipakai di `<button>`, hapus aja fungsinya di `<button>` supaya gak error

2024-02-26 07:33 UTC, raihanizar requested changes
@BrezyBaihaqi logic edit & create udah good, file management udah lebi rapi

catatan:
- file `ListEvents.jsx` and `DetailEvents.jsx` yg berubah banyak, tapi cuma titik koma sama tanda kutip aja, baiknya gak dimasukkan di commit ini, karena gak relevan. Tolong di revert ya perubahannya supaya yg relevan aja
- nama component utk update event baiknya gak perlu pake "use", supaya gak ketuker dengan hooks

semangat!

2024-02-26 08:35 UTC, BrezyBaihaqi commented
mas untuk editevent nama componentnys EditEvent tanpa use, bener belum? terus yg nomor 1 kan ini udah d commit cara batalinnya gmana ya?

2024-02-26 14:42 UTC, raihanizar approved these changes
@BrezyBaihaqi oke udah mantap, tapi tolong prettiernya bandel itu wkwkwk

2024-02-26 14:42 UTC, merged